### ISSUE TITLE
black dependency breaks python3.5 install

### ISSUE THREAD

**Issue by bmschmidt** [jasonlaska/spherecluster#12]
`black` is only available for python3.6 and higher; its presence in `requirements.txt` makes installation of this package on python3.5 (under, for me, Ubuntu 16.04 LTS) fail.

Since `black` doesn't seem to be used by the package (just in the dev process?) maybe it can be removed from `requirements.txt`? Doing so makes local installation work fine for me.

**Comment by jasonlaska** [comment]
Thanks!  I'll separate the dev requirements out.

**Comment by jasonlaska** [comment]
Also, this was originally developed for python 2.7 so there should be no problem specific to python 3.5.

**Comment by bmschmidt** [comment]
Yes, the local install works great for me without it on 3.5. Thanks for your good work!

**Comment by jasonlaska** [comment]
This has been updated, you can grab the latest (0.1.7) at https://github.com/jasonlaska/spherecluster/releases/tag/0.1.7 or from pypi.
