### ISSUE TITLE
Using Spherical clustering for Mini-Batch K-Means

### ISSUE THREAD

**Issue by Fazel94** [jasonlaska/spherecluster#19]
Thank you for sharing this great package, 
I wanted to experiment with K-Means on a big enough data set that it would require a Mini-Batch version of K-Means,
Do you have any direction for me to follow on and extend your implementation to Mini-Batch?

**Comment by jasonlaska** [comment]
If you are just looking to implement spherical K-means (and not movMF), then all you need to do is normalize the cluster centers in each iteration as in https://github.com/jasonlaska/spherecluster/blob/develop/spherecluster/spherical_kmeans.py#L88,  you should be able to extend any existing implementation of k-means for this, including sklearn's latest.  My code for skmeans is meant mostly as a reference.

(Remember your input vectors should also be normalized).
