### ISSUE TITLE
TypeError: Expected sequence or array-like, got <class 'NoneType'>

### ISSUE THREAD

**Issue by fredia** [jasonlaska/spherecluster#22]
self.clus.fit(self.data)
  File "D:\工程\知识图谱自动构建\AutoBuild\venv\lib\site-packages\spherecluster\spherical_kmeans.py", line 363, in fit
    return_n_iter=True,
  File "D:\工程\知识图谱自动构建\AutoBuild\venv\lib\site-packages\spherecluster\spherical_kmeans.py", line 189, in spherical_k_means
    random_state=random_state,
  File "D:\工程\知识图谱自动构建\AutoBuild\venv\lib\site-packages\spherecluster\spherical_kmeans.py", line 39, in _spherical_kmeans_single_lloyd
    sample_weight = _check_sample_weight(X, sample_weight)
  File "D:\工程\知识图谱自动构建\AutoBuild\venv\lib\site-packages\sklearn\utils\validation.py", line 1215, in _check_sample_weight
    n_samples = _num_samples(X)
  File "D:\工程\知识图谱自动构建\AutoBuild\venv\lib\site-packages\sklearn\utils\validation.py", line 147, in _num_samples
    raise TypeError(message)
TypeError: Expected sequence or array-like, got <class 'NoneType'>
------------------------------------------------------------------------------
hi，the params of " _check_sample_weight(sample_weight, X, dtype=None):" defined by sklearn is "sample_weight,X" ,but in spherical_kmeans(line 39) call this fuction : "_check_sample_weight(X, sample_weight)" . does the order of params lead to this?

**Comment by bdpedigo** [comment]
I'm having the same error, using `spherecluster 0.1.7` from PyPI, and `sklearn 0.22`. It looks like this issue was created with the upgrade from `sklearn 0.21` as I just ran the same code with 0.21 and it ran fine.

I would be happy to look into this and make a PR, if you'd like, just let me know @jasonlaska!

**Comment by jasonlaska** [comment]
@bdpedigo a PR would be great!

**Comment by fredia** [comment]
@bdpedigo   thanks, you have done me a great favor！ Looking forward to your PR.

**Comment by joseph-sch** [comment]
I second all these comments. In the call to `_check_sample_weight`, the order of arguments is inconsistent with the function definition.

The call:
 https://github.com/jasonlaska/spherecluster/blob/0ef69cd1f7a52fb65bd714d381fb48ff181c3819/spherecluster/spherical_kmeans.py#L39

For reference, the code of `_check_sample_weight`:

https://github.com/scikit-learn/scikit-learn/blob/4ad4cc632ec37f7b5e05bde66dd675dd4ef7c545/sklearn/utils/validation.py#L1133

So the `sample_weight` argument should come first and the `X` argument should come second.

**Comment by jasonlaska** [comment]
I've merged a patch for this into the develop branch.  Will appear in next release but feel free to pul develop for your more immediate purposes.
