### ISSUE TITLE
ImportError: cannot import name '_k_means'

### ISSUE THREAD

**Issue by Randool** [jasonlaska/spherecluster#26]
Hi. I install spherecluster using`pip install spherecluster` successfully in Ubuntu 18.04. But when I call `from spherecluster import SphericalKMeans`, I got an ImportError.

```
Traceback (most recent call last):
  File "LM/vectors_cluster.py", line 9, in <module>
    from spherecluster import SphericalKMeans
  File "/path_to_anaconda/lib/python3.6/site-packages/spherecluster/__init__.py", line 2, in <module>
    from .spherical_kmeans import SphericalKMeans
  File "/path_to_anaconda/lib/python3.6/site-packages/spherecluster/spherical_kmeans.py", line 16, in <module>
    from sklearn.cluster import _k_means
ImportError: cannot import name '_k_means'
```

Here is my environmental information:

| Package | Version |
| - | - |
| numpy | 1.14.3 |
| scipy | 1.1.0 |
| scikit-learn | 0.22.2.post1 |
| pytest | 3.5.1 |
| nose | 1.3.7 |
| joblib | 0.14.1 |
| spherecluster | 0.1.7 | 

If anyone can help me, I would really appreciate it!

**Comment by rtrad89** [comment]
I'm not 100% sure, but it appears that `sklearn 0.22.1` has introduced some changes that made the aforesaid code line to fail, namely:
```
from sklearn.cluster import import _k_means
```

I got the code running using:
```
from sklearn.cluster import _kmeans as _k_means  # _k_means directly caused the error
```
But I am getting some new errors in the function `_check_sample_weight`, more precisely at the line:
```
n_samples = _num_samples(X)
```
The error reads:
```
TypeError: Expected sequence or array-like, got <class 'NoneType'>
```

Despite that, I hope this is of any help.

**Comment by rtrad89** [comment]
I'm not 100% sure, but it appears that `sklearn 0.22.1` has introduced some changes that made the aforesaid code line to fail, namely:
```
from sklearn.cluster import _k_means
```

I got the code running using:
```
from sklearn.cluster import _kmeans as _k_means  # _k_means directly caused the error
```
But I am getting some new errors in the function `_check_sample_weight`, more precisely at the line:
```
n_samples = _num_samples(X)
```
The error reads:
```
TypeError: Expected sequence or array-like, got <class 'NoneType'>
```

Despite that, I hope this is of any help.

**Comment by Randool** [comment]
@rtrad89 Thanks. I also made the same changes to the code and got the same 'TypeError'. Hope for the next version.

**Comment by rtrad89** [comment]
> 
> 
> @rtrad89 Thanks. I also made the same changes to the code and got the same 'TypeError'. Hope for the next version.

@Randool would you please confirm whether you have the latest `spherecluster` version, `0.1.7` that is? Because I noticed something may be the culprit.

In my local version of the aforementioned `spherecluster` (`0.1.7`), the [call in `spherical_kmeans.py`](https://github.com/jasonlaska/spherecluster/blob/0.1.7/spherecluster/spherical_kmeans.py#L39) is:
```
sample_weight = _check_sample_weight(X, sample_weight)
```
While in the [online github version](https://github.com/jasonlaska/spherecluster/blob/develop/spherecluster/spherical_kmeans.py#L41), it is in the correct form:
```
sample_weight = _check_sample_weight(sample_weight, X)
```

**Comment by Randool** [comment]
@rtrad89 I read the source code and found this change, so I commented this line. But I remember the result is still disappointing.

**Comment by YBZh** [comment]
It seems that downgrading the sklearn to the older version of 0.20.0 can solve the problem.
`conda install scikit-learn=0.20.0`

**Comment by Randool** [comment]
> It seems that downgrading the sklearn to the older version of 0.20.0 can solve the problem.
> `conda install scikit-learn=0.20.0`

Thanks! That's the right solution!

**Comment by glicerico** [comment]
This is a workaround, not a solution.
A side-effect of downgrading to 0.20.0 is that the OPTICS clustering algorithm is not available anymore.
Can we re-open this issue, and find a proper solution for it?

**Comment by glicerico** [comment]
Oh, I see this has been [taken care of](https://github.com/jasonlaska/spherecluster/compare/master...develop) in the develop branch of the original repo, as @rtrad89 pointed out above.
So the next package should solve this issue, and for now one has to compile the repo code to have it working properly.
I tested with OPTICS in the develop version and it works fine :)
@Randool, sorry, I think this issue can indeed be closed.

**Comment by Randool** [comment]
haha, looking forward to the next version :> @glicerico

**Comment by rtrad89** [comment]
> 
> 
> This is a workaround, not a solution.
> A side-effect of downgrading to 0.20.0 is that the OPTICS clustering algorithm is not available anymore.
> Can we re-open this issue, and find a proper solution for it?

Just reporting that downgrading only to `0.22.0` doesn't have this side effect.

If you are using `Anaconda3`, you can write:

```
 conda install scikit-learn=0.22.0
```
